services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
     - .:/app:cached

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  node_modules:
